layers: [7, 8, 9, 10, 24, 25, 26, 27, 40, 41]
track_ml:
    dir:      /global/cfs/projectdirs/m3443/usr/xju/heptrkx/codalab/inputs/train_all
    detector: /global/cfs/projectdirs/m3443/usr/xju/heptrkx/codalab/inputs/detector.csv

doublet_training:
    batch_size: 512
    epochs: 50
    eff_cut: 0.95
    model_output_dir: /global/cfs/projectdirs/atlas/xju/tracking/PairsFromNN/model10evtsTF2
    model: fully_connected_classifier
    features: ['dphi', 'dz', 'dr', 'phi_slope', 'z0', 'deta', 'deta1', 'dphi1']
    cuts: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

graph_definition:
    node_features: ['x', 'y', 'z']
    edge_features: ['deta', 'dphi']
    n_eta: 1
    n_phi: 1

gnn_training:
    n_eta: 1
    n_phi: 1
    tfrec_name: '*_*.tfrec'
    tfrec_dir_cloud: 'gs://gnn-v1/notavaiable'
    tfrec_dir_local: /global/cscratch1/sd/xju/heptrkx/kaggle/ReducedGraphSize/Embeded_doublets_padding
    output_dir: /global/cfs/projectdirs/atlas/xju/tracking/PairsFromEmbeded/GNNSmallerPadGraph
    tpu_output_dir: "gs://gnn-v1/model"
    prod_name: Data_Distributed_2GPUs
    model_name: vary2
    parameters:
        batch_size: 2
        n_iters: 8
        learning_rate: 0.0005
        real_weight: 2.
        fake_weight: 1.
        epochs: 2
