layers: [7, 8, 9, 10, 24, 25, 26, 27, 40, 41]
track_ml:
    dir:      /global/cfs/projectdirs/m3443/usr/xju/heptrkx/codalab/inputs/train_all
    detector: /global/cfs/projectdirs/m3443/usr/xju/heptrkx/codalab/inputs/detector.csv

doublet_training:
    batch_size: 512
    epochs: 50
    eff_cut: 0.95
    model_output_dir: /global/cfs/projectdirs/atlas/xju/tracking/PairsFromNN/model10evtsTF2
    model: fully_connected_classifier
    features: ['dphi', 'dz', 'dr', 'phi_slope', 'z0', 'deta', 'deta1', 'dphi1']
    cuts: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

# full hit features
# cluster: ['leta', 'lphi', 'lx', 'ly', 'lz', 'geta', 'gphi']
# position: [x, y, z, |z|, phi, theta, eta, r, r3, layer]
# full edge features
# ['dr', 'dz', 'cottheta', 'dphi', 'zorg', 'phi_slope', 'deta', 'deta1', 'dphi1']
gnn_training:
    hit_files:
        - /global/cscratch1/sd/xju/heptrkx/codalab/inputs/hitfiles/evt21001_test.h5
        - /global/cscratch1/sd/xju/heptrkx/codalab/inputs/hitfiles/evt22011-10events.h5
    doublet_files:
        - /global/cscratch1/sd/xju/heptrkx/codalab/inputs/doublet_files/doublets-evt21001_test.h5
        - /global/cscratch1/sd/xju/heptrkx/codalab/inputs/doublet_files/doublets-evt22011-10events.h5
    n_eta: 2
    n_phi: 10
    # node_features: ['x', 'y', 'z', 'r', 'eta', 'phi', 'geta', 'gphi']
    node_features: ['x', 'y', 'z']
    edge_features: ['deta', 'dphi']
    output_dir: /global/cfs/projectdirs/atlas/xju/tracking/PairsFromNN/GNNEdgeClassifier
    model_name: default 
    prod_name: EdgeFeatures
    log_name: big.log
    input_type: 'data_dict'
    parameters:
        time_lapse:  30 # how often save checkpoint in seconds
        batch_size: 1
        iterations: 200000
        iter_per_job: 200000
        n_iters: 8
        learning_rate: 0.001
        real_weight: 100.0
        fake_weight: 1.