trainingInput:
    scaleTier: CUSTOM
    masterType: n1-highmem-2
    workerType: cloud_tpu
    workerCount: 1 
    workerConfig:
        tpuTfVersion: "2.1"
        acceleratorConfig:
            type: TPU_V2
            count: 8