#!/usr/bin/env python
import glob
import os
import pickle

def check_dir(filedir):
    base_filename = os.path.join(filedir, 'event{}_{}')
    evtids = []
    nevts = 9000
    evts_per_record = 100

    evts_per_file = []
    nevts_added = 0
    for ievt in range(nevts):
        evtid = 1000 + ievt
        file_name = base_filename.format(evtid, 0) + ".npz"
        if not os.path.exists(file_name):
            continue
        nevts_added += 1
        evts_per_file.append(evtid)
        if nevts_added % evts_per_record == 0:
            evtids.append(evts_per_file)
            evts_per_file = []
            nevts_added = 0
    return evtids

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Write out event id")
    add_arg = parser.add_argument
    # /project/projectdirs/m3443/usr/dtmurnane/doublets/high_fullsplit 
    # /global/cscratch1/sd/xju/heptrkx/codalab/daniel_doublets.pkl
    add_arg("file_dir", help="directories")
    add_arg("outname", help='output file')
    args = parser.parse_args()

    evtids = check_dir(args.file_dir)
    print(len(evtids))
    with open(args.outname, 'wb') as f:
        pickler = pickle.Pickler(f)
        pickler.dump(evtids)