#!/usr/bin/env python 
"""
merge multiple h5 files into one
"""

if __name__ == "__main__":
    import argparse
    import time
    import os
    import pandas as pd
    from heptrkx.utils import is_df_there

    parser = argparse.ArgumentParser(description='merge mutliple h5 files into one')
    add_arg = parser.add_argument
    add_arg('outname', help='output file')
    add_arg('file_names', nargs='+', help='file names')
    args = parser.parse_args()

    outname = args.outname
    file_names = args.file_names
    if is_df_there(outname):
        print("{} is there".format(outname))
    else:
        print("Merging to {}".format(outname))

    with pd.HDFStore(outname, 'w') as out_store:
        for file_name in file_names:
            print("Adding {}".format(file_name))
            with pd.HDFStore(file_name) as store:
                for key in store.keys():
                    out_store[key] = store[key]