#!/usr/bin/env python


if __name__ == "__main__":
    import pandas as pd
    import numpy as np
    import argparse

    parser = argparse.ArgumentParser(description='trim the fat doublet file')
    add_arg = parser.add_argument
    add_arg("input_file", help='input doublet file name')
    add_arg('out_file', help='output doublet file name')
    args = parser.parse_args()

    selected_features =  [
        'evtid', 'solution',
        'hit_id_in', 'hit_id_out',
        'dphi', 'dz', 'dr', 'phi_slope', 'z0', 'deta', 'deta1', 'dphi1',
        # 'x_in', 'y_in', 'z_in',
        # 'x_out', 'y_out' 'z_out',
        # 'hit_idx_in', 'hit_idx_out',
        # 'layer_in', 'layer_out',
    ]
    with pd.HDFStore(args.out_file, 'w') as out_store:
        with pd.HDFStore(args.input_file, 'r') as in_store:
            for key in in_store.keys():
                df = in_store[key]
                df = df[selected_features]
                out_store[key] = df

    print("{}\n\tconverted to\n{}\nwith following {} features kept".format(args.input_file, args.out_file, len(selected_features)))
    print(selected_features)