
# subdirectory of base_dir storing true pairs and all pairs
doublets_for_training:
    base_dir: /global/cscratch1/sd/xju/heptrkx/codalab/outputs/pairs
    true_pairs: merged_true_pairs # only true pairs
    all_pairs: all_pairs # all pairs, used for training, testing, for Graph

doublet_training:
    batch_size: 512
    epochs: 6
    eff_cut: 0.98
    model_output_dir: /global/cscratch1/sd/xju/heptrkx/codalab/outputs/doublet_NN_onlyPos_old_features
    model: fully_connected_classifier
    features: ['dphi', 'dz', 'dr', 'phi_slope', 'z0', 'deta']
    bkg_from_evtid: 21000

doublets_for_graph:
    selected: /global/cscratch1/sd/xju/heptrkx/codalab/outputs/seed_studies/location_old_features
